export const DEVTOOLS_PANEL_CONNECT = 'DEVTOOLS_PANEL_CONNECT';
export const DEVTOOLS_PANEL_MESSAGE = 'DEVTOOLS_PANEL_MESSAGE';
export const DEVTOOLS_PANEL_INIT = 'DEVTOOLS_PANEL_INIT';
export const DEVTOOLS_PANEL_OPEN = 'DEVTOOLS_PANEL_OPEN';

export const CONTENT_SCRIPT_CONNECT = 'CONTENT_SCRIPT_CONNECT';
export const CONTENT_SCRIPT_MESSAGE = 'CONTENT_SCRIPT_MESSAGE';
export const CONTENT_SCRIPT_DISCONNECT = 'CONTENT_SCRIPT_DISCONNECT';

export const RX_DEVTOOL_START = 'RX_DEVTOOL_START';
export const RX_DEVTOOL_CUSTOM_EVENT = 'RX_DEVTOOL_CUSTOM_EVENT';
export const OBSERVABLE_CREATED = 'OBSERVABLE_CREATED';
export const OBSERVABLE_SUBSCRIBE = 'OBSERVABLE_SUBSCRIBE';
export const OBSERVABLE_NEXT = 'OBSERVABLE_NEXT';
export const OBSERVABLE_ERROR = 'OBSERVABLE_ERROR';
export const OBSERVABLE_COMPLETE = 'OBSERVABLE_COMPLETE';
export const OBSERVABLE_UNSUBSCRIBE = 'OBSERVABLE_UNSUBSCRIBE';

export const RESET_STORE = 'RESET_STORE';
