export const DEVTOOLS_PANEL_CONNECT = 'DEVTOOLS_PANEL_CONNECT';
export const DEVTOOLS_PANEL_MESSAGE = 'DEVTOOLS_PANEL_MESSAGE';
export const DEVTOOLS_PANEL_INIT = 'DEVTOOLS_PANEL_INIT';
export const DEVTOOLS_PANEL_OPEN = 'DEVTOOLS_PANEL_OPEN';

export const CONTENT_SCRIPT_CONNECT = 'CONTENT_SCRIPT_CONNECT';
export const CONTENT_SCRIPT_MESSAGE = 'CONTENT_SCRIPT_MESSAGE';
